name: graphql_to_dart
description: A simple dart package to generate complete Dart models from a GraphQL endpoint by leveraging GraphQL introspection API.
version: 1.1.0
homepage: https://github.com/vikram25897/graphql_to_dart
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.1
  graphql: ^5.1.1
  recase: ^4.0.0

